-- Aluminum Foil Container Wrinklewall Rectangle Products - Batch 3
INSERT INTO products (id, slug, sku, name_i18n, description_i18n, category_id, images, technical_specs, introduction, status, created_at) VALUES

-- C2 Series
(gen_random_uuid(), 'aluminum-foil-container-c2-120', 'C2-120', '{"en": "Aluminum Foil Container C2-120", "de": "Aluminiumfolien-Behälter C2-120", "es": "Contenedor de Papel de Aluminio C2-120", "fr": "Conteneur en Papier d''Aluminium C2-120"}', '{"en": "Wrinklewall rectangular aluminum foil container C2-120", "de": "Rechteckiger Aluminiumfolien-Behälter mit gewellten Wänden C2-120", "es": "Contenedor rectangular de papel de aluminio de pared arrugada C2-120", "fr": "Conteneur rectangulaire en papier d''aluminium à parois plissées C2-120"}', (SELECT id FROM categories WHERE slug = 'aluminum-foil-container-wrinklewall'), '["product_img/Aluminum-Foil/Container/Wrinklewall/Rectangle/C2-120/c2-120.webp", "product_img/Aluminum-Foil/Container/Wrinklewall/Rectangle/C2-120/c2-120-2.webp", "product_img/Aluminum-Foil/Container/Wrinklewall/Rectangle/C2-120/c2-120-3.webp"]', '{"material": "Aluminum Foil", "type": "Container", "wall": "Wrinklewall", "shape": "Rectangle"}', '{"en": "High-quality aluminum foil container with wrinkled walls", "de": "Hochwertiger Aluminiumfolien-Behälter mit gewellten Wänden", "es": "Contenedor de papel de aluminio de alta calidad con paredes arrugadas", "fr": "Conteneur en papier d''aluminium de haute qualité avec parois plissées"}', 'active', NOW()),

(gen_random_uuid(), 'aluminum-foil-container-c2-180', 'C2-180', '{"en": "Aluminum Foil Container C2-180", "de": "Aluminiumfolien-Behälter C2-180", "es": "Contenedor de Papel de Aluminio C2-180", "fr": "Conteneur en Papier d''Aluminium C2-180"}', '{"en": "Wrinklewall rectangular aluminum foil container C2-180", "de": "Rechteckiger Aluminiumfolien-Behälter mit gewellten Wänden C2-180", "es": "Contenedor rectangular de papel de aluminio de pared arrugada C2-180", "fr": "Conteneur rectangulaire en papier d''aluminium à parois plissées C2-180"}', (SELECT id FROM categories WHERE slug = 'aluminum-foil-container-wrinklewall'), '["product_img/Aluminum-Foil/Container/Wrinklewall/Rectangle/C2-180/c2-180.webp", "product_img/Aluminum-Foil/Container/Wrinklewall/Rectangle/C2-180/c2-180-2.webp", "product_img/Aluminum-Foil/Container/Wrinklewall/Rectangle/C2-180/c2-180-3.webp"]', '{"material": "Aluminum Foil", "type": "Container", "wall": "Wrinklewall", "shape": "Rectangle"}', '{"en": "High-quality aluminum foil container with wrinkled walls", "de": "Hochwertiger Aluminiumfolien-Behälter mit gewellten Wänden", "es": "Contenedor de papel de aluminio de alta calidad con paredes arrugadas", "fr": "Conteneur en papier d''aluminium de haute qualité avec parois plissées"}', 'active', NOW()),

-- C3 Series
(gen_random_uuid(), 'aluminum-foil-container-c3-250', 'C3-250', '{"en": "Aluminum Foil Container C3-250", "de": "Aluminiumfolien-Behälter C3-250", "es": "Contenedor de Papel de Aluminio C3-250", "fr": "Conteneur en Papier d''Aluminium C3-250"}', '{"en": "Wrinklewall rectangular aluminum foil container C3-250", "de": "Rechteckiger Aluminiumfolien-Behälter mit gewellten Wänden C3-250", "es": "Contenedor rectangular de papel de aluminio de pared arrugada C3-250", "fr": "Conteneur rectangulaire en papier d''aluminium à parois plissées C3-250"}', (SELECT id FROM categories WHERE slug = 'aluminum-foil-container-wrinklewall'), '["product_img/Aluminum-Foil/Container/Wrinklewall/Rectangle/C3-250/c3-250.webp", "product_img/Aluminum-Foil/Container/Wrinklewall/Rectangle/C3-250/c3-250-2.webp", "product_img/Aluminum-Foil/Container/Wrinklewall/Rectangle/C3-250/c3-250-3.webp"]', '{"material": "Aluminum Foil", "type": "Container", "wall": "Wrinklewall", "shape": "Rectangle"}', '{"en": "High-quality aluminum foil container with wrinkled walls", "de": "Hochwertiger Aluminiumfolien-Behälter mit gewellten Wänden", "es": "Contenedor de papel de aluminio de alta calidad con paredes arrugadas", "fr": "Conteneur en papier d''aluminium de haute qualité avec parois plissées"}', 'active', NOW()),

-- C4 Series
(gen_random_uuid(), 'aluminum-foil-container-c4-450', 'C4-450', '{"en": "Aluminum Foil Container C4-450", "de": "Aluminiumfolien-Behälter C4-450", "es": "Contenedor de Papel de Aluminio C4-450", "fr": "Conteneur en Papier d''Aluminium C4-450"}', '{"en": "Wrinklewall rectangular aluminum foil container C4-450", "de": "Rechteckiger Aluminiumfolien-Behälter mit gewellten Wänden C4-450", "es": "Contenedor rectangular de papel de aluminio de pared arrugada C4-450", "fr": "Conteneur rectangulaire en papier d''aluminium à parois plissées C4-450"}', (SELECT id FROM categories WHERE slug = 'aluminum-foil-container-wrinklewall'), '["product_img/Aluminum-Foil/Container/Wrinklewall/Rectangle/C4-450/c4-450.webp", "product_img/Aluminum-Foil/Container/Wrinklewall/Rectangle/C4-450/c4-450-2.webp", "product_img/Aluminum-Foil/Container/Wrinklewall/Rectangle/C4-450/c4-450-3.webp"]', '{"material": "Aluminum Foil", "type": "Container", "wall": "Wrinklewall", "shape": "Rectangle"}', '{"en": "High-quality aluminum foil container with wrinkled walls", "de": "Hochwertiger Aluminiumfolien-Behälter mit gewellten Wänden", "es": "Contenedor de papel de aluminio de alta calidad con paredes arrugadas", "fr": "Conteneur en papier d''aluminium de haute qualité avec parois plissées"}', 'active', NOW()),

-- C130 Series
(gen_random_uuid(), 'aluminum-foil-container-c130-750', 'C130-750', '{"en": "Aluminum Foil Container C130-750", "de": "Aluminiumfolien-Behälter C130-750", "es": "Contenedor de Papel de Aluminio C130-750", "fr": "Conteneur en Papier d''Aluminium C130-750"}', '{"en": "Wrinklewall rectangular aluminum foil container C130-750", "de": "Rechteckiger Aluminiumfolien-Behälter mit gewellten Wänden C130-750", "es": "Contenedor rectangular de papel de aluminio de pared arrugada C130-750", "fr": "Conteneur rectangulaire en papier d''aluminium à parois plissées C130-750"}', (SELECT id FROM categories WHERE slug = 'aluminum-foil-container-wrinklewall'), '["product_img/Aluminum-Foil/Container/Wrinklewall/Rectangle/C130-750/c130-750.webp", "product_img/Aluminum-Foil/Container/Wrinklewall/Rectangle/C130-750/c130-750-2.webp", "product_img/Aluminum-Foil/Container/Wrinklewall/Rectangle/C130-750/c130-750-3.webp"]', '{"material": "Aluminum Foil", "type": "Container", "wall": "Wrinklewall", "shape": "Rectangle"}', '{"en": "High-quality aluminum foil container with wrinkled walls", "de": "Hochwertiger Aluminiumfolien-Behälter mit gewellten Wänden", "es": "Contenedor de papel de aluminio de alta calidad con paredes arrugadas", "fr": "Conteneur en papier d''aluminium de haute qualité avec parois plissées"}', 'active', NOW()),

-- C142 Series
(gen_random_uuid(), 'aluminum-foil-container-c142-1000', 'C142-1000', '{"en": "Aluminum Foil Container C142-1000", "de": "Aluminiumfolien-Behälter C142-1000", "es": "Contenedor de Papel de Aluminio C142-1000", "fr": "Conteneur en Papier d''Aluminium C142-1000"}', '{"en": "Wrinklewall rectangular aluminum foil container C142-1000", "de": "Rechteckiger Aluminiumfolien-Behälter mit gewellten Wänden C142-1000", "es": "Contenedor rectangular de papel de aluminio de pared arrugada C142-1000", "fr": "Conteneur rectangulaire en papier d''aluminium à parois plissées C142-1000"}', (SELECT id FROM categories WHERE slug = 'aluminum-foil-container-wrinklewall'), '["product_img/Aluminum-Foil/Container/Wrinklewall/Rectangle/C142-1000/c142-1000.webp", "product_img/Aluminum-Foil/Container/Wrinklewall/Rectangle/C142-1000/c142-1000-2.webp", "product_img/Aluminum-Foil/Container/Wrinklewall/Rectangle/C142-1000/c142-1000-3.webp"]', '{"material": "Aluminum Foil", "type": "Container", "wall": "Wrinklewall", "shape": "Rectangle"}', '{"en": "High-quality aluminum foil container with wrinkled walls", "de": "Hochwertiger Aluminiumfolien-Behälter mit gewellten Wänden", "es": "Contenedor de papel de aluminio de alta calidad con paredes arrugadas", "fr": "Conteneur en papier d''aluminium de haute qualité avec parois plissées"}', 'active', NOW()),

-- C144 Series
(gen_random_uuid(), 'aluminum-foil-container-c144-1400', 'C144-1400', '{"en": "Aluminum Foil Container C144-1400", "de": "Aluminiumfolien-Behälter C144-1400", "es": "Contenedor de Papel de Aluminio C144-1400", "fr": "Conteneur en Papier d''Aluminium C144-1400"}', '{"en": "Wrinklewall rectangular aluminum foil container C144-1400", "de": "Rechteckiger Aluminiumfolien-Behälter mit gewellten Wänden C144-1400", "es": "Contenedor rectangular de papel de aluminio de pared arrugada C144-1400", "fr": "Conteneur rectangulaire en papier d''aluminium à parois plissées C144-1400"}', (SELECT id FROM categories WHERE slug = 'aluminum-foil-container-wrinklewall'), '["product_img/Aluminum-Foil/Container/Wrinklewall/Rectangle/C144-1400/c144-1400.webp", "product_img/Aluminum-Foil/Container/Wrinklewall/Rectangle/C144-1400/c144-1400-2.webp", "product_img/Aluminum-Foil/Container/Wrinklewall/Rectangle/C144-1400/c144-1400-3.webp"]', '{"material": "Aluminum Foil", "type": "Container", "wall": "Wrinklewall", "shape": "Rectangle"}', '{"en": "High-quality aluminum foil container with wrinkled walls", "de": "Hochwertiger Aluminiumfolien-Behälter mit gewellten Wänden", "es": "Contenedor de papel de aluminio de alta calidad con paredes arrugadas", "fr": "Conteneur en papier d''aluminium de haute qualité avec parois plissées"}', 'active', NOW());